apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  labels:
    app: nginx-metrics
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: nginx-metrics
