resources:
- ../../base

configMapGenerator:
- literals:
  - ENV=prod
  name: mysql-config
  behavior: merge

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: secret.yaml
